config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }



  # get 'items' => 'public/items#index'
  # get 'items/:id' => 'public/items#show'



  # get 'cart_items' => 'public/cart_items#index'
  # patch 'cart_items/:id' => 'public/cart_items#update'


  # post 'cart_items' => 'public/cart_items#create'

  #get 'orders/new' => 'public/orders#new'

  #get 'orders/complete' => 'public/orders#complete'
  #post 'orders' => 'public/orders#create'
  #get 'orders' => 'public/orders#index'
  #get 'orders/:id' => 'public/orders#show'

  # get 'addresses/:id/edit' => 'public/addresses#edit'
  # get 'addresses' => 'public/addresses#index'
  # post 'addresses' => 'public/addresses#create'
  # patch 'addresses/:id' => 'public/addresses#update'
  # delete 'addresses/:id' => 'public/addresses#destroy'

  scope module: :public do
    root :to =>"homes#top"
    get "about"=>"homes#about"
    resources :addresses, only:[:index, :edit, :create, :destroy, :update]
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'
    get 'items/:id/index_by_genre' => 'items#index_by_genre', as: 'index_by_genre'
    resources :items, only:[:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only:[:index, :update, :destroy, :create]
    post 'orders/comfirm' => 'orders#comfirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders, only:[:new, :complete, :create, :index, :show]
  end

  namespace :admin do
    get ""=>"homes#top"
    resources :order_details, only: [:update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]

  end


  # get 'items' => 'items#index'
  # get 'items/new' => 'items#new'
  # post 'items' => 'items#create'
  # get 'items/:id' => 'items#show'
  # get 'items/:id/edit' => 'items#edit'
  # patch 'items/:id' => 'items#update'

  # get 'genres' => 'genres#index'
  # post 'genres' => 'genres#create'
  # get 'genres/:id/edit' => 'genres#edit'
  # patch 'genres/:id' => 'genres#update'

  # get 'customers' => 'customers#index'
  # get 'customers/:id' => 'customers#show'
  # get 'customers/:id/edit' => 'customers#edit'
  # patch 'customers/:id' => 'customers#update'

  # get 'orders/:id' => 'orders#show'
  # patch 'orders/:id' => 'orders#update'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_datails
  has_many :cart_items
  belongs_to :genre
  has_one_attached :image
  
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def tax_include_price
    (price*1.1).round(0)
  end
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    def index
      @items = Item.all
      @items = Item.page(params[:page])
    end

    def new
      @item = Item.new
      @genres = Genre.all
    end

    def show
      @item = Item.find(params[:id])
      @genre = @item.genre
    end

    def create
      @item = Item.new(item_params)
      @item.save
      redirect_to admin_item_path(@item.id)
    end

    def edit
      @item = Item.find(params[:id])
      @genres = Genre.all
    end

    def update
      @item = Item.find(params[:id])
      @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    end

    private

    def item_params
      params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
    end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/_index.html.erb
<div class="col-8">
  
  <table class='table table-striped'>
    <thead>
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.id  %></td>
          <td><u><%= link_to item.name ,admin_item_path(item.id), class: "text-dark"  %></u></td>
          <td><%= item.price %></td>
          <td><%= item.genre.name %></td>
          <td>
            <% if item.is_active == false %>
              <span class="text-success"><strong>販売中</strong></span>
            <% else %>
              <span class="text-secondary"><strong>販売停止中</strong></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      
      <label class="my-4 h4">商品編集</label>
      <%= form_with model: @item, url: admin_item_path(@item.id), method: :patch do |f| %>
        <div class="form-group">
          <label for="image">商品画像</label>
          <%= f.file_field :image, accept: "image/*", id: "image", class: "form-control-file image" %>
        </div>
        <div class="form-group">
          <%= f.label :name, "商品名：" %>
          <%= f.text_field :name, autofocus: true, class: "form-control" %>
        </div>
        <div class="form-group">
          <span>商品説明</span>
          <%= f.text_area :introduction, class: "form-control" %>
        </div>
        <div class="form-group">
          <span>ジャンル</span>
          <%= f.collection_select :genre_id, @genres, :id, :name, {prompt: "--選択してください--"}, {class: "form-control input-sm"} %>
        </div>
        <div class="form-group">
          <span>税抜価格</span>
          <%= f.number_field :price, class: "form-control" %>円
        </div>
        <div class="form-group">
          <span>販売ステータス</span>
          <%= f.radio_button :is_active, 0, checked: true %>販売中 <%= f.radio_button :is_active, 1 %>販売停止中
        </div>
        <div class="form-group">
          <%= f.submit "変更を保存", class: "btn btn-success" %>
        </div>
      <% end %>
      
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class='container mt-5'>

  <div class='row mb-3'>
    <div class="col-8 h1">商品一覧</div>
    <div class="col-1 offset-3">
      <%= link_to new_admin_item_path do %>
        <a class="btn btn-light btn-lg" href="/admin/items/new" role="button">＋</a>
      <% end %>
    </div>
  </div>
  
  <div class='row'>
    <%= render 'index', item: @item %>
    <%= paginate @items %>
  </div>

</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      
      <label class="my-4 h4">商品新規登録</label>
      <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
        <table class="table">
          <tr>
            <td>商品画像</td>
            <td><%= f.file_field :image, accept: "image/*", id: "image", class: "form-control-file image" %></td>
          </tr>
          <tr>
            <td>商品名</td>
            <td><%= f.text_field :name, autofocus: true, class: "form-control" %></td>
          </tr>
          <tr>
            <td>商品説明</td>
            <td><%= f.text_area :introduction, class: "form-control" %></td>
          </tr>
          <tr>
            <td>ジャンル名</td>
            <td><%= f.collection_select :genre_id, @genres, :id, :name, {prompt: "--選択してください--"}, {class: "form-control input-sm"} %></td>
          </tr>
          <tr>
            <td>税抜価格</td>
            <td><%= f.number_field :price, class: "form-control" %>円</td>
          </tr>
          <tr>
            <td>販売ステータス</td>
            <td><%= f.radio_button :is_active, 0, checked: true %>販売中 <%= f.radio_button :is_active, 1 %>販売停止中</td>
          </tr>
          <tr>
            <td></td>
            <td><%= f.submit "新規登録", class: "btn btn-success" %></div>
            </td>
          </tr>
        </table>
      <% end %>
      
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class='container mt-5'>
  
  <div class='row mb-3'>
    <div class= "h1">商品詳細</div>
  </div>

   <div class="row mb-3">
     <div class="col-3">
       <%= image_tag @item.get_image(200, 200) %>
     </div>

     <div class="col">
        <table class="table table-bordered">
        <tbody>
          <tr>
            <th>商品名</th>
            <th><%= @item.name %></th>
          </tr>
          <tr>
            <th>商品説明</th>
            <th><%= @item.introduction %></th>
          </tr>
          <tr>
            <th>ジャンル</th>
            <th><%= @genre.name %></th>
          </tr>
          <tr>
            <th>税込価格<br>(税抜価格)</th>
            <th><%= (@item.price * 1.1).round(0) %>(<%= @item.price %>)円</th>
          </tr>
          <tr>
            <th>販売ステータス</th>
            <th>
              <% if @item.is_active == false %>
                <span class="text-success">販売中</span>
              <% else %>
                <span class="text-secondary">販売停止中</span>
              <% end %>
            </th>
          </tr>
        </tbody>
      </table>
     </div>
   </div>
   
  <div class="row">
      <div class="mx-auto">
        <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-success" %>
      </div>
  </div>
  
</div>