config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }



  # get 'items' => 'public/items#index'
  # get 'items/:id' => 'public/items#show'



  # get 'cart_items' => 'public/cart_items#index'
  # patch 'cart_items/:id' => 'public/cart_items#update'


  # post 'cart_items' => 'public/cart_items#create'

  #get 'orders/new' => 'public/orders#new'

  #get 'orders/complete' => 'public/orders#complete'
  #post 'orders' => 'public/orders#create'
  #get 'orders' => 'public/orders#index'
  #get 'orders/:id' => 'public/orders#show'

  # get 'addresses/:id/edit' => 'public/addresses#edit'
  # get 'addresses' => 'public/addresses#index'
  # post 'addresses' => 'public/addresses#create'
  # patch 'addresses/:id' => 'public/addresses#update'
  # delete 'addresses/:id' => 'public/addresses#destroy'

  scope module: :public do
    root :to =>"homes#top"
    get "about"=>"homes#about"
    resources :addresses, only:[:index, :edit, :create, :destroy, :update]
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'
    get 'items/:id/index_by_genre' => 'items#index_by_genre', as: 'index_by_genre'
    resources :items, only:[:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only:[:index, :update, :destroy, :create]
    post 'orders/comfirm' => 'orders#comfirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders, only:[:new, :complete, :create, :index, :show]
  end

  namespace :admin do
    get ""=>"homes#top"
    resources :order_details, only: [:update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]

  end


  # get 'items' => 'items#index'
  # get 'items/new' => 'items#new'
  # post 'items' => 'items#create'
  # get 'items/:id' => 'items#show'
  # get 'items/:id/edit' => 'items#edit'
  # patch 'items/:id' => 'items#update'

  # get 'genres' => 'genres#index'
  # post 'genres' => 'genres#create'
  # get 'genres/:id/edit' => 'genres#edit'
  # patch 'genres/:id' => 'genres#update'

  # get 'customers' => 'customers#index'
  # get 'customers/:id' => 'customers#show'
  # get 'customers/:id/edit' => 'customers#edit'
  # patch 'customers/:id' => 'customers#update'

  # get 'orders/:id' => 'orders#show'
  # patch 'orders/:id' => 'orders#update'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  def full_name
    self.last_name + " " + self.first_name
  end

  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end

  private

  def customer_params
    params.require(:customer).permit(:full_name, :full_name_kana, :email, :postal_code, :address, :telephone_number, :is_deleted, :last_name_kana, :first_name_kana, :last_name, :first_name)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row mt-3 mb-4">
    <h5><%= @customer.full_name %>さんの会員詳細</h5>
  </div>

 <div class="row">
    <div class="col-6 col-sm-2">会員ID</div>
     <div class="col-6 col-sm-2"><%= @customer.id %></div>
 </div>
 <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch do |f| %>
 <div class="row mt-2">
    <div class="col-6 col-sm-2">氏名</div>
     <label><%= f.text_field :last_name %></label>
    <div class="col-6 col-sm-2">
      <label><%= f.text_field :first_name %></label>
    </div>
 </div>

 <div class="row">
    <div class="col-6 col-sm-2">フリガナ</div>
    <label><%= f.text_field :last_name_kana %></label>
    <div class="col-6 col-sm-2">
    <label><%= f.text_field :first_name_kana %></label>
    </div>
 </div>
 <div class="row">
     <div class="col-6 col-sm-2">郵便番号</div>
     <label><%= f.text_field :postal_code %></label>
 </div>
 <div class="row">
     <div class="col-6 col-sm-2">住所</div>
     <label><%= f.text_field :address %></label>
 </div>
 <div class="row">
     <div class="col-6 col-sm-2">電話番号</div>
     <label><%= f.text_field :telephone_number %></label>
 </div>
 <div class="row">
     <div class="col-6 col-sm-2">メールアドレス</div>
     <label><%= f.email_field :email, autofocus: true, autocomplete: "email" %></label>
 </div>

 <div class="row">
     <div class="col-6 col-sm-2">会員ステータス</div>
     <%= f.radio_button :is_deleted, 0, checked: true %>有効　<%= f.radio_button :is_deleted, 1 %>退会
 </div>

 <div class="row mt-4">
  <div class="col-6 col-sm-2"></div>
  <div class="col-6 col-sm-2"><%= f.submit '変更を保存', class: "btn btn-success" %></div>
 </div>

 <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    会員情報
  </div>


  <div>
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td><%= link_to customer.full_name, admin_customer_path(customer.id) %></td>
          <td><%= customer.email %></td>
          <td>
            <% if customer.is_deleted == false %>
           <span class="text-success"><strong>有効</strong></span>
            <% else %>
           <span class="text-secondary"><strong>退会</strong></span>
            <% end %></td>
        </tr>
        <% end %>
      </tbody>
      <%= paginate @customers %>
    </table>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row mt-3 mb-4">
    <h5><%= @customer.full_name %>さんの会員詳細</h5>
  </div>

  <div class="row mb-3">
    <div class="col-6 col-sm-2">会員ID</div>
    <div class="col-6 col-sm-2"><%= @customer.id %></div>
  </div>

  <div class="row mb-3">
    <div class="col-6 col-sm-2">氏名</div>
    <div class="col-6 col-sm-2"><%= @customer.full_name %></div>
  </div>

  <div class="row mb-3">
    <div class="col-6 col-sm-2">フリガナ</div>
    <div class="col-6 col-sm-2"><%= @customer.full_name_kana %></div>
  </div>

  <div class="row mb-3">
    <div class="col-6 col-sm-2">郵便番号</div>
    <div class="col-6 col-sm-2"><%= @customer.postal_code %></div>
  </div>

  <div class="row mb-3">
    <div class="col-6 col-sm-2">住所</div>
    <div class="col-6 col-sm-2"><%= @customer.address %></div>
  </div>

  <div class="row mb-3">
    <div class="col-6 col-sm-2">電話番号</div>
    <div class="col-6 col-sm-2"><%= @customer.telephone_number %></div>
  </div>

  <div class="row mb-3">
    <div class="col-6 col-sm-2">メールアドレス</div>
    <div class="col-6 col-sm-2"><%= @customer.email%></div>
  </div>

  <div class="row mb-3">
    <div class="col-6 col-sm-2">会員ステータス</div>
    <div class="col-6 col-sm-2">
    <% if @customer.is_deleted == false %>
    <span class="text-success"><strong>有効</strong></span>
    <% else %>
    <span class="text-secondary"><strong>退会</strong></span>
    <% end %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-6 col-sm-2"></div>
    <div class="col-6 col-sm-2"><%= link_to '編集する', edit_admin_customer_path(@customer), class: "btn btn-success" %></div>
    <div class="col-6 col-sm-3"><%= link_to '注文履歴一覧を見る', admin_path, class: "btn btn-primary" %></div>
  </div>

</div>