config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }



  # get 'items' => 'public/items#index'
  # get 'items/:id' => 'public/items#show'



  # get 'cart_items' => 'public/cart_items#index'
  # patch 'cart_items/:id' => 'public/cart_items#update'


  # post 'cart_items' => 'public/cart_items#create'

  #get 'orders/new' => 'public/orders#new'

  #get 'orders/complete' => 'public/orders#complete'
  #post 'orders' => 'public/orders#create'
  #get 'orders' => 'public/orders#index'
  #get 'orders/:id' => 'public/orders#show'

  # get 'addresses/:id/edit' => 'public/addresses#edit'
  # get 'addresses' => 'public/addresses#index'
  # post 'addresses' => 'public/addresses#create'
  # patch 'addresses/:id' => 'public/addresses#update'
  # delete 'addresses/:id' => 'public/addresses#destroy'

  scope module: :public do
    root :to =>"homes#top"
    get "about"=>"homes#about"
    resources :addresses, only:[:index, :edit, :create, :destroy, :update]
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'
    get 'items/:id/index_by_genre' => 'items#index_by_genre', as: 'index_by_genre'
    resources :items, only:[:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only:[:index, :update, :destroy, :create]
    post 'orders/comfirm' => 'orders#comfirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders, only:[:new, :complete, :create, :index, :show]
  end

  namespace :admin do
    get ""=>"homes#top"
    resources :order_details, only: [:update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]

  end


  # get 'items' => 'items#index'
  # get 'items/new' => 'items#new'
  # post 'items' => 'items#create'
  # get 'items/:id' => 'items#show'
  # get 'items/:id/edit' => 'items#edit'
  # patch 'items/:id' => 'items#update'

  # get 'genres' => 'genres#index'
  # post 'genres' => 'genres#create'
  # get 'genres/:id/edit' => 'genres#edit'
  # patch 'genres/:id' => 'genres#update'

  # get 'customers' => 'customers#index'
  # get 'customers/:id' => 'customers#show'
  # get 'customers/:id/edit' => 'customers#edit'
  # patch 'customers/:id' => 'customers#update'

  # get 'orders/:id' => 'orders#show'
  # patch 'orders/:id' => 'orders#update'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many:items
  validates :name, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.create(genre_params)
    if @genre.save
      redirect_to edit_admin_genre_path(@genre.id)
    else
      render:index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render 'edit'
    end
  end
  
  private

  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/_index.html.erb
<div class="border border-dark pb-5">
  <p class="border-bottom border-dark text-center">ジャンル検索</p>
<% genres.each do |genre| %>
  <div class="pl-3 pb-2">
    <%= link_to genre.name, index_by_genre_path(genre.id) %>
  </div>
<% end %>
</div>

app/views/admin/genres/edit.html.erb
<div class="container">
    <h2>ジャンル編集</h2>
  <div class="row">
    <div class= "col-md-6 mt-5">
      <%= form_with model: @genre, url: admin_genre_path, method: :patch do |f| %>
      <table class="table mt-5">
         <tr>
           <td>
              <%= f.label :name, "ジャンル名" %>
           </td>
           <td>
              <%= f.text_field :name, class: "form-control" %>
           </td>
           <td>
              <%= f.submit "変更を保存", class: "btn btn-success" %>
           </td>
         </tr>
       </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
    <h2>ジャンル一覧・追加</h2>
    <%= form_with model: @genre, url: admin_genres_path do |f| %>
  <div class='container px-5 px-sm-0'>
    <div class='row'>
      <div class="mt-5"><%= f.label :name, "ジャンル名" %></div>
      <div class="mt-5 ml-3 col-3 "><%= f.text_field :name, autofocus: true, autocomplete: "genres", placeholder: "ジャンル名", class:"form-control" %></div>
      <div class="mt-5 ml-3 col-3"><%= f.submit "新規登録", class:"btn btn-success col-5" %></div>
    </div>
  </div>
    <% end %>
    
    
    <div class='container px-1 px-sm-0 mt-5'>
    <div class='row'>
      <div class="col-3">
        <table class="table table-hover table-inverse">
            <thead>
                <tr>
                    <th>ジャンル</th>
                    <th></th>
                    <th colspan="3"></th>
                </tr>
            </thead>
            <tbody>
                <% @genres.each do |genre| %>
                    <tr>
                        <td><%= genre.name %></td>
                        <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-sm btn-success" %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    　</div>
    </div>
    </div>
</div>