config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }



  # get 'items' => 'public/items#index'
  # get 'items/:id' => 'public/items#show'



  # get 'cart_items' => 'public/cart_items#index'
  # patch 'cart_items/:id' => 'public/cart_items#update'


  # post 'cart_items' => 'public/cart_items#create'

  #get 'orders/new' => 'public/orders#new'

  #get 'orders/complete' => 'public/orders#complete'
  #post 'orders' => 'public/orders#create'
  #get 'orders' => 'public/orders#index'
  #get 'orders/:id' => 'public/orders#show'

  # get 'addresses/:id/edit' => 'public/addresses#edit'
  # get 'addresses' => 'public/addresses#index'
  # post 'addresses' => 'public/addresses#create'
  # patch 'addresses/:id' => 'public/addresses#update'
  # delete 'addresses/:id' => 'public/addresses#destroy'

  scope module: :public do
    root :to =>"homes#top"
    get "about"=>"homes#about"
    resources :addresses, only:[:index, :edit, :create, :destroy, :update]
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'
    get 'items/:id/index_by_genre' => 'items#index_by_genre', as: 'index_by_genre'
    resources :items, only:[:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only:[:index, :update, :destroy, :create]
    post 'orders/comfirm' => 'orders#comfirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders, only:[:new, :complete, :create, :index, :show]
  end

  namespace :admin do
    get ""=>"homes#top"
    resources :order_details, only: [:update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]

  end


  # get 'items' => 'items#index'
  # get 'items/new' => 'items#new'
  # post 'items' => 'items#create'
  # get 'items/:id' => 'items#show'
  # get 'items/:id/edit' => 'items#edit'
  # patch 'items/:id' => 'items#update'

  # get 'genres' => 'genres#index'
  # post 'genres' => 'genres#create'
  # get 'genres/:id/edit' => 'genres#edit'
  # patch 'genres/:id' => 'genres#update'

  # get 'customers' => 'customers#index'
  # get 'customers/:id' => 'customers#show'
  # get 'customers/:id/edit' => 'customers#edit'
  # patch 'customers/:id' => 'customers#update'

  # get 'orders/:id' => 'orders#show'
  # patch 'orders/:id' => 'orders#update'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  has_many :images, dependent: :destroy
  
  has_one_attached :image
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  
def tax_include_price
  (item.price*1.1).round(0)
end

def subtotal
  tax_include_price*amount
end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  def full_name
    self.last_name + " " + self.first_name
  end

  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many:items
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_datails
  has_many :cart_items
  belongs_to :genre
  has_one_attached :image
  
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def tax_include_price
    (price*1.1).round(0)
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: {waiting_for_deposit: 0, payment_confirmation: 1, in_production: 2, preparing_to_ship: 3, sent: 4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: { not_startable: 0, wait_product: 1, in_product: 2, finish_product: 3}
  
  def subtotal
    price*amount
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.create(genre_params)
    if @genre.save
      redirect_to edit_admin_genre_path(@genre.id)
    else
      render:index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render 'edit'
    end
  end
  
  private

  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.order(id: "DESC").page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    def index
      @items = Item.all
      @items = Item.page(params[:page])
    end

    def new
      @item = Item.new
      @genres = Genre.all
    end

    def show
      @item = Item.find(params[:id])
      @genre = @item.genre
    end

    def create
      @item = Item.new(item_params)
      @item.save
      redirect_to admin_item_path(@item.id)
    end

    def edit
      @item = Item.find(params[:id])
      @genres = Genre.all
    end

    def update
      @item = Item.find(params[:id])
      @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    end

    private

    def item_params
      params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :authenticate_admin!, except: [:top]
  #before_action :authenticate_customer!, except: [:top, :about,]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    customers_my_page_path
  end


  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkGithub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header class="sticky-top">
    <div class="border-bottom">
    <div class="navbar navbar-expand-md navbar-dark bg-danger bg-gradient">
          <a href="/"><img src="/assets/nagano cake.png" alt="", width="200", height="40"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon bg-dark"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
          <% if customer_signed_in? %>
            <li class="nav-item" style="padding:10px;">
              <%= link_to "マイページ", customers_my_page_path, class: 'nav-link text-danger border bg-white' %>
            </li>
            <li class="nav-item" style="padding:10px;,background-color: white;">
              <%= link_to "商品一覧", items_path, class: 'nav-link text-danger border bg-white' %>
            </li>
            <li class="nav-item" style="padding:10px;">
              <%= link_to "カート", cart_items_path, class: 'nav-link text-danger border bg-white' %>
            </li>
            <li class="nav-item" style="padding:10px;">
              <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-danger border bg-white' %>
            </li>
            <% elsif admin_signed_in? %>
            <li class="nav-item" style="padding:10px;">
              <%= link_to "商品一覧", admin_items_path, class: 'nav-link text-danger border bg-white' %>
            </li>
            <li class="nav-item" style="padding:10px;">
              <%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-danger border bg-white' %>
            </li>
            <li class="nav-item" style="padding:10px;">
              <%= link_to "注文履歴一覧", admin_path, class: 'nav-link text-danger border bg-white' %>
            </li>
            <li class="nav-item" style="padding:10px;">
              <%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link text-danger border bg-white' %>
            </li>
              <li class="nav-item" style="padding:10px;">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-danger border bg-white' %>
              </li>
            <% else %>
            <li class="nav-item" style="padding:10px;">
              <%= link_to "About", about_path, class: 'nav-link text-danger border bg-white' %>
            </li>
            <li class="nav-item" style="padding:10px;">
              <%= link_to "商品一覧", items_path, class: 'nav-link text-danger border bg-white' %>
            </li>
            <li class="nav-item" style="padding:10px;">
              <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-danger border bg-white' %>
            </li>
            <li class="nav-item" style="padding:10px;">
              <%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-danger border bg-white' %>
            </li>
            <% end %>
          </ul>
      </div>
      </div>
    </div>
  </header>

  <body>
    <%= yield %>
  </body>
</html>